Handle GPID (openrtb endpoint)
sharethrough/Prebid.js-inventory-growth pull request #1110
Opened 2021-06-23 17:36 UTC by epechuzal

Sister PR to #1107, this time for openRTB endpoint.

From a talk with STX they want the param to be in `imp.ext.gpid`, so I added it there.

2021-06-23 17:52 UTC, maphe requested changes

2021-06-23 17:52 UTC, maphe commented on modules/sharethroughBidAdapter.js
> +      }
we usually try to avoid sending empty objects in the query, we could do that instead
```suggestion
      const impression = {};

      const gpid = utils.deepAccess(bidReq, 'ortb2Imp.ext.data.pbadslot');
      if (gpid) {
        impression.ext = { gpid: gpid };
      }
```

2021-06-23 18:04 UTC, maphe approved these changes

2021-06-23 19:06 UTC, merged

2021-09-18 00:27 UTC, sjfields100 commented
Hey guys, looks like this update may have broken sharethrough on our site-- it doesn't work above prebid v 5.13. Did any required configurations change for sharethrough or is it just the pkey that is still required? It works below v 5.13.

Here is a test page:
https://wishlist.indy100.com/37-gadgets-that-make-cleaning-10x-easier/?test=cleanup&pbjs_debug=true&5.13.0

Sceenshot of errors in network tab of DOM:
<img width="1078" alt="Screen Shot 2021-09-17 at 4 20 12 PM" src="https://user-images.githubusercontent.com/28765487/133865683-c59d94eb-35ee-4508-acce-71ab7ba429f9.png">

2021-09-20 18:08 UTC, epechuzal commented
> Hey guys, looks like this update may have broken sharethrough on our site-- it doesn't work above prebid v 5.13. Did any required configurations change for sharethrough or is it just the pkey that is still required? It works below v 5.13.
> 
> Here is a test page:
> https://wishlist.indy100.com/37-gadgets-that-make-cleaning-10x-easier/?test=cleanup&pbjs_debug=true&5.13.0
> 
> Sceenshot of errors in network tab of DOM:
> <img alt="Screen Shot 2021-09-17 at 4 20 12 PM" width="1078" src="https://user-images.githubusercontent.com/28765487/133865683-c59d94eb-35ee-4508-acce-71ab7ba429f9.png">

Required configuration should not have changed. I do not get HTTP 400 responses when I visit your test page either.