Send parameter indicating the protocol of the requesting page
sharethrough/Prebid.js-inventory-growth pull request #128
Opened 2019-11-28 01:03 UTC by madma

- `secure` parameter will equal `true` if the requesting page uses `https` and `false` otherwise

Story: [#169736764](https://www.pivotaltracker.com/story/show/169736764)

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2019-12-05 17:38 UTC, epechuzal requested changes

2019-12-05 17:38 UTC, epechuzal commented on modules/sharethroughBidAdapter.js
> +      query.secure = nonHttp || (sharethroughInternal.getProtocol().indexOf('https') > -1);
I don't get this bit - are non-http requests deemed secure?

2019-12-05 18:05 UTC, javadreamer commented on modules/sharethroughBidAdapter.js
> +      query.secure = nonHttp || (sharethroughInternal.getProtocol().indexOf('https') > -1);
@epechuzal - sometimes the url can resolve to 'about:blank' and the protocol ends up being 'about'.  The thinking is that its safer to default to secure rather than the other way around, since this flag will affect, potentially the assets sent back by the DSP.

In the case of a secure page, sending back insecure assets won't work.  However, in the case of a non-secure page, sending back secure assets even though they don't need to be secure, WILL work.

2019-12-05 18:06 UTC, javadreamer approved these changes

2019-12-05 19:15 UTC, madma commented on modules/sharethroughBidAdapter.js
> +      query.secure = nonHttp || (sharethroughInternal.getProtocol().indexOf('https') > -1);
to be safe, i'm going to try redirecting / forcing a win with the updated adapter code. stay tuned.

2019-12-05 23:46 UTC, madma commented on modules/sharethroughBidAdapter.js
> +      query.secure = nonHttp || (sharethroughInternal.getProtocol().indexOf('https') > -1);
tested adapter update locally: only checked http**s** sites, since i couldn't find an http site running prebid -- most of our pubs seem to be redirecting to secure versions of their sites :) 

confirming the update is working as expected and sending the `secure` param.

2019-12-23 17:03 UTC, madma commented
Closing this pull request. Our changes were merged into `Prebid.js` and released under version Prebid client version `3.1.0`: https://github.com/prebid/Prebid.js/releases/tag/3.1.0.

2019-12-23 17:04 UTC, closed without merging