[PGE-178206477] Ingest First Party Data and send to Ad Server
sharethrough/Prebid.js-inventory-growth pull request #1292
Opened 2021-11-10 19:17 UTC by maphe

Doc: https://docs.prebid.org/features/firstPartyData.html#how-it-works

https://sharethrough.atlassian.net/browse/PGE-178206477

2021-11-10 19:23 UTC, epechuzal requested changes

2021-11-10 19:23 UTC, epechuzal commented on modules/sharethroughBidAdapter.js
> +    req.user = firstPartyData.user ?? {};
You might get linting issues with this when you raise the PR to pbjs (the `??` operator is not supported everywhere).

I wrote a `nullish(input, def)` method at the bottom of the file, so you can replace `??` usages
```ts
// replace this
value ?? default-if-null

// with this
nullish(value, default-if-null)
```

2021-12-10 16:00 UTC, pierreted90 approved these changes

2021-12-13 18:28 UTC, maphe commented
Closing internal PR, reopening against Prebid repo

2021-12-13 18:28 UTC, closed without merging