Auto-detect safeframe and properly skip/insert JS accordingly
sharethrough/Prebid.js-inventory-growth pull request #13
Opened 2019-08-13 01:41 UTC by javadreamer

The sharethrough bidder will still respect `iframe` being set to `true`.  In the case that it isn't set or set to true, the adapter will add JS functionality to the ad markup that will programmatically auto-detect whether or not the STR ad has been served to a safeframe and add iframe buster and clientJS accordingly.

* adds a `sharethroughInternal` exported const that allows for stubbing/testing and ability to avoid redefining logic in specs
* adds function for detecting whether ad is in a safeframe or not
* adds code that programmatically inserts sfp.js (if SFP js hasn't been loaded)
* adds code that programmatically inserts sfp-iframe-buster.js (if safeframe not auto-detected)
* updates adapter version to 3.1.0 from 3.0.1 (been a hot sec since we incremented the version)

2019-08-14 20:47 UTC, madma requested changes
Just one question about function naming / intent.

2019-08-14 20:47 UTC, madma commented on modules/sharethroughBidAdapter.js
> +      size = req.strData.iframeSize
Good clean up. It was unnecessary to check specifically for value of `undefined`.

2019-08-14 20:47 UTC, madma commented on modules/sharethroughBidAdapter.js
> +  `;
Good clean up with adding missing `;`s.

2019-08-14 20:47 UTC, madma commented on modules/sharethroughBidAdapter.js
> +function isInSafeframe () {
This seems like a misnomer. Should this be `isInIframe` instead?

SafeFrames are a subset of iframe elements that employ the IAB SafeFrame API. To check if we are in a SafeFrame, we would need to traverse the window hierarchy until we find or don't find the `$sf` object that exposes SafeFrame functionality (behavioral functionality that allows the SafeFrame to do things that an ordinary iframe cannot, such as expand/collapse).

2019-08-14 21:40 UTC, javadreamer commented on modules/sharethroughBidAdapter.js
> +function isInSafeframe () {
The method detects if the iframe has access to the top frame, by forcing a DOMException and sets a window variable accordingly.   It assumes its in an iframe already, but the raison d'etre of the method is to indicate to the c code that follows its execution that the code is in a safeframe.

2019-08-14 22:06 UTC, madma commented on modules/sharethroughBidAdapter.js
> +function isInSafeframe () {
To clarify, any cross origin iframe will not have access to `window.top` unless its src domain is explicitly whitelisted by the server of the parent window with an appropriate CORS policy (less clear on these details, personally).

2019-08-16 22:49 UTC, madma approved these changes
Looks good to go! Nice that we will now be able to render inside an iframe even when a pub has not provided the `iframe` param but we do not have access to the top window -- will be interesting to track any change to render rate.

2019-08-19 17:13 UTC, merged