[PGE-178206904] Send Transaction ID to STX
sharethrough/Prebid.js-inventory-growth pull request #1544
Opened 2022-08-31 18:35 UTC by maphe

`source.tid` is transaction id at the request level
`bidReq.ortb2Imp` may carry a transaction id at the impression level (`imp.ext.tid`)

Followed recommendations provided by contributors here: https://github.com/prebid/Prebid.js/issues/8573

PGE-178206904

2022-08-31 19:19 UTC, balbinas approved these changes

2022-08-31 20:33 UTC, javadreamer requested changes
No changes per se, just a requested sanity check with STX.

That said.  Thank you for including the notes to the github issue with Pat McCann.   Very detailed conversation and great questions and general back and forth.   👍

2022-08-31 20:33 UTC, javadreamer commented on modules/sharethroughBidAdapter.js
> +      mergeDeep(impression, bidReq.ortb2Imp);
Are we sure that we want this - since it merges everrything in from the bid request?    Will STX properly ignore what its not expecting to receive in the bid request?   Are we sure that there risk is minimal of impression requests being potentially larger than expected (full of additional fields that mean nothing to the exchange?)

I recommend sanity checking, if you haven't already done so, this approach with STX Core, specifically via the universal endpoint.   Not opposed per se, but want to make sure  supply and exchange are aligned on this change.

2022-08-31 21:44 UTC, maphe commented on modules/sharethroughBidAdapter.js
> +      mergeDeep(impression, bidReq.ortb2Imp);
Well, it doesn't merge "everything", it merges what Prebid allows the publishers to inject in the requests, from the doc:
> `ortb2Imp` is used to signal OpenRTB Imp objects at the adUnit grain. Similar to the global ortb2 field used for global first party data configuration, but specific to this adunit. The `ortb2Imp` object currently supports first party data including the Prebid Ad Slot and the interstitial signal.

from which everything lives in the `ext` field.

I can ask STX but I believe we already have a some fields that STX does not care about but DSPs do, so it would fall into the same category. I think the universal endpoint mostly acts as a passthrough since both input and output are openRTB formatted, allowing us at the adapter level to leverage as much Prebid features as we can and let DSPs read or ignore as they will.

2022-08-31 21:57 UTC, maphe commented on modules/sharethroughBidAdapter.js
> +      mergeDeep(impression, bidReq.ortb2Imp);
Conversation opened with STX here: https://sharethrough.slack.com/archives/G03A4C37B/p1661982990805279

2022-09-13 15:57 UTC, javadreamer approved these changes

2022-09-13 20:20 UTC, maphe commented
Opened PR on official public repo: https://github.com/prebid/Prebid.js/pull/8988

2022-09-13 20:20 UTC, closed without merging