Ig 178207483  remove video defaults
sharethrough/Prebid.js-inventory-growth pull request #1617
Opened 2024-09-04 21:50 UTC by jefftmahoney

IG team: here are the video-logic updates I plan on including in a PR to Prebid.  (Going to initiate a cross-fork PR, as we normally do, from the Prebid repo.)

Including here for your review and reference.  I will be closing this "local" PR after people have had a chance to look at it (and/or spot any problems I might have introduced!).

2024-09-05 15:21 UTC, maxime-dupuis requested changes

2024-09-05 15:21 UTC, maxime-dupuis commented on test/spec/modules/sharethroughBidAdapter_spec.js
> +        it('should not set array-defined properties if non-array values are provided', () => {
⚠️ I think the test shouldn't be concerned with the implementation details ("array-defined"), it should focus on the behaviour (test the pizza, not the kitchen)
And it should explain WHY some have defaults and some don't

If I understand correctly, instead of assigning default values here in the adapter, we'll now set them on the exchange side.

I propose:

```suggestion
        it('should not set default values to properties with exchange-side defaults', () => {
```

And the test just above would become

```
'should set default values to properties without exchange-side defaults'
```

2024-09-05 15:21 UTC, maxime-dupuis commented on test/spec/modules/sharethroughBidAdapter_spec.js
> +          expect(videoImp.protocols).to.be.undefined;
⚠️ could you test all the properties without defaults?

2024-09-05 15:21 UTC, maxime-dupuis commented on test/spec/modules/sharethroughBidAdapter_spec.js
>            expect(videoImp.companionad).to.be.undefined;
⚠️ these undefined values (without defaults) should be moved to the next test

2024-09-05 15:21 UTC, maxime-dupuis commented on modules/sharethroughBidAdapter.js
> +                return;
Out of scope for this PR, but is there a way to do error handling?
I think the user might like to know when a property is discarded because it's invalid and why, so they can fix it.
What do you think?

2024-09-05 15:21 UTC, maxime-dupuis commented on modules/sharethroughBidAdapter.js
> +          const propertiesToConsider = [
⚠️ there's 2 patterns for pos/topframe/w/h VS the rest of properties. Something feels off because they're not that different except for having or not having default values

Would following the previous pattern work?

For example,
```
skip: nullish(videoRequest.skip, 0),
```
Becomes
```
skip: nullish(videoRequest.skip, undefined),
```

It would be simpler, but maybe I missed a trap

2024-09-05 15:21 UTC, maxime-dupuis commented on modules/sharethroughBidAdapter.js
> +            const propTakesArrayValues = ['api', 'mimes', 'playbackmethod', 'protocols'].includes(prop);
Nitpick: I had to reread it a couple of times to understand the meaning. Would you be ok with:

```suggestion
            const propIsTypeArray = ['api', 'mimes', 'playbackmethod', 'protocols'].includes(prop);
```

2024-09-05 19:37 UTC, jefftmahoney commented on modules/sharethroughBidAdapter.js
> +                return;
I'm actually not sure that that IS out of scope!  :)  There's actually a pattern Prebid uses where `logError()`, `logWarn()` and `logInfo()` calls are employed to inform consumers / pubs that they're doing something wrong.  That would be a good thing to do here, so that publishers would be aware that their errant values are being discarded.  I'll add that.

2024-09-05 19:38 UTC, jefftmahoney commented on test/spec/modules/sharethroughBidAdapter_spec.js
> +          expect(videoImp.protocols).to.be.undefined;
Yes, that would be a good idea.  Will do that.

2024-09-05 19:42 UTC, jefftmahoney commented on modules/sharethroughBidAdapter.js
> +          const propertiesToConsider = [
That's a good suggestion, except that assigning `unassigned` as a value to a property I think would trip up the exchange, because the code there expects either 1) a property to exist with a value, or 2) the property to not exist at all (on the JSON payload received from the request).  In the latter circumstance, it's all set up, with its mapping, to apply the property with a default value.  But having the property already present with `null` or `undefined` I think would wreck that.

2024-09-05 20:30 UTC, maxime-dupuis commented on modules/sharethroughBidAdapter.js
> +          const propertiesToConsider = [
gave it a go, you're right the prop will remain there
![image](https://github.com/user-attachments/assets/1b10444d-10d2-4647-9476-333259f68e9c)

consider this comment optional
But if you think of a way to simplify and get rid of special cases it would be a plus
Possibly slap this after the assignments to get rid of undefined properties? https://stackoverflow.com/a/38340374/3212785
```
Object.keys(impression.video).forEach(key => {
  if (impression.video[key] === undefined) {
    delete impression.video[key];
  }
});
```

2024-09-06 23:13 UTC, jefftmahoney commented on modules/sharethroughBidAdapter.js
> +            const propTakesArrayValues = ['api', 'mimes', 'playbackmethod', 'protocols'].includes(prop);
Updated.

2024-09-09 14:30 UTC, jefftmahoney commented on test/spec/modules/sharethroughBidAdapter_spec.js
> +        it('should not set array-defined properties if non-array values are provided', () => {
Cool - I renamed the phrase on the test to talk more generally about what it was trying to do.

2024-09-09 14:35 UTC, jefftmahoney commented on modules/sharethroughBidAdapter.js
> +          const propertiesToConsider = [
The 2-pattern setup is not great, but I'm going to leave it for now because there's also a plan to overhaul the adapter with oRTBConverter later (which will redo all of this).

2024-09-09 14:40 UTC, maxime-dupuis approved these changes
👍

2024-09-09 15:26 UTC, closed without merging