CCPA support for bid requests and user syncs
sharethrough/Prebid.js-inventory-growth pull request #217
Opened 2020-01-07 23:09 UTC by epechuzal

### Summary of changes
- pull US privacy signal from bidderRequest object and add it to our payload
- add the signal to all user syncs

[Story](https://www.pivotaltracker.com/story/show/169331745)

2020-01-09 01:34 UTC, javadreamer commented on modules/sharethroughBidAdapter.js
> +        syncs.push({ type: 'image', url: url + syncParams });
Are we confident that there are already other params in the URL?   Otherwise, we'll need to add the `?`.   That may be overkill depending on the examples of cookie sync urls that we see in the wild.  Thoughts?

2020-01-09 21:24 UTC, epechuzal commented on modules/sharethroughBidAdapter.js
> +        syncs.push({ type: 'image', url: url + syncParams });
I looked at a couple other adapters and they went with this; I think we can assume params will be present, but I do not know this for sure either. Where do the URLs come from? Since they're in the Butler response, do they exist in our DB somewhere? Or are they provided by something else?

2020-01-09 21:51 UTC, madma requested changes
looks good. just a couple of minor comments i left and also the following questions:

1. there will need to be a corresponding PR in the documentation repo so that we're listed as an adapter that supports us privacy / ccpa. see https://prebid.org/dev-docs/modules/consentManagementUsp.html#adapter-integration

2. how's our test coverage? are we still maintaining 80%+ coverage? lmk if you want to pair on running this if you haven't done so already -- i think the instructions for checking test coverage are in the readme.

2020-01-09 21:51 UTC, madma commented on modules/sharethroughBidAdapter.js
> +    const syncParams = (uspConsent) ? `&us_privacy=${uspConsent}` : '';
nitpick: parens `()` not needed in the ternary condition.

2020-01-09 21:51 UTC, madma commented on modules/sharethroughBidAdapter.js
> +        syncs.push({ type: 'image', url: url + syncParams });
good call. i think it'd be worthwhile to use a regex to determine whether there are other params / if we need the `?` in the url.

2020-01-09 21:51 UTC, madma commented on modules/sharethroughBidAdapter.js
> +        syncs.push({ type: 'image', url: url + syncParams });
speaking of adding params to the user sync urls, should `gdprConsent` data be added as params, as well? it's outside the scope of the current story, and given the redundancy we discovered for user syncs (i.e. that user sync pixels are also processed by our client sdk) and the fact that gdpr consent data gets sent to butler in `buildRequests()`, this might not be necessary to do here. just wanted to raise this question @javadreamer .

2020-01-09 21:51 UTC, madma commented on test/spec/modules/sharethroughBidAdapter_spec.js
> +        /data-str-native-key="pKey" data-stx-response-name="str_response_bidId"/);
🥇

2020-01-10 02:04 UTC, javadreamer commented on modules/sharethroughBidAdapter.js
> +        syncs.push({ type: 'image', url: url + syncParams });
@madma - we should avoid anything not in the scope of CCPA.  we are not concerned about GDPR in the context of this story, in particular since it is such a low volume of traffic (judging from the SignalFX dashboard).

@epechuzal - 99.5% of the time or more there will be params.   we can punt on this.

2020-01-13 19:52 UTC, madma approved these changes
looks good. had to refresh myself on viewing test coverage. jotting down here for future reference.
1. `gulp test-coverage`
2. `gulp view-coverage`
3. http://localhost:1999/modules/sharethroughBidAdapter.js.html

2020-02-13 16:51 UTC, closed without merging

2020-02-13 16:51 UTC, epechuzal commented
Closing; has been merged on prebid master already